### ISSUE TITLE
I have test code in WiderFace,the result is amazing! I want to know,in the  ShanghaiTech data,can i train the model by the released training code?

### ISSUE THREAD

**Issue by dreamFinoa** [WangyiNTU/Point-supervised-crowd-detection#1]

**Comment by WangyiNTU** [comment]
Yes, it needs to change some parameters. We will release the training and testing code for Shanghaitech soon.

**Comment by jieruyao49** [comment]
I reported an error when running. I suspect it is an environment version problem. Can you provide your installation environment version. Thank you very much.
