### ISSUE TITLE
Is this code still working in 2021?

### ISSUE THREAD

**Issue by anwarhikarii** [WangyiNTU/Point-supervised-crowd-detection#2]
Im sorry if my question sounds disrespectful, I've tried everything in the books(im still a student btw). Using windows i cant install tensorflow 1.14 while using python 2.7. But when i use python 3.6 the code cannot be executed and there is change that has to be made, and my knowledge in python is really low to convert it. Is there any tips on how can i run this.

**Comment by WangyiNTU** [comment]
The main problem is Windows. Please use Linux (like Ubuntu) since all codes were developed and run smoothly on it. I don't know the potential problems in Windows.
`pip install tensorflow-gpu==1.14.`

**Comment by anwarhikarii** [comment]
Are there any specific version of Ubuntu you would like to suggest me

**Comment by anwarhikarii** [comment]
Starting from scratch...
Traceback (most recent call last):
  File "train_wider.py", line 91, in <module>
    with open(cache_path, 'rb') as fid:
IOError: [Errno 21] Is a directory: 'data/cache/widerface/train'


i have run it in ubuntu but this error appeared when i try to run the train_wider.py

**Comment by WangyiNTU** [comment]
@anwarhikarii You need to prepare the dataset at first by
`python LUDA_generate_wider.py`
where it generates 'data/cache/widerface/train'. Please refer to readme.

**Comment by anwarhikarii** [comment]
Hello, I still cant run this, sorry for asking too much, but i manage to get past the training and testing part, but when i try to use the plot prediction detection code, it gave me this error, 

  File "plot_wider_detections.py", line 68, in <module>
    bboxes = bboxes[bboxes[:,4] > thr]
IndexError: too many indices for array

what number should i change it to? 

btw, i changed the epoch to 50 since i only use 2 gpu

**Comment by WangyiNTU** [comment]
@anwarhikarii I think you can print bboxes out or single-step debug with Pycharm. Then, showing the results. Maybe, due to some wrong settings in the previous codes, bboxes are empty. Please debug it.
