### ISSUE TITLE
Is the network structure for SH already in the current repository? 

### ISSUE THREAD

**Issue by donggoing** [WangyiNTU/Point-supervised-crowd-detection#3]
I don't seem to find a network structure in resnet.py that matches the diagram in the paper.

**Comment by WangyiNTU** [comment]
@donggoing The structure can refer to this link.
> https://github.com/WangyiNTU/Point-supervised-crowd-detection/blob/701750757adf7015d091a114acbc0f43da2d2772/keras_csp/resnet50_full_res.py#L205

**Comment by donggoing** [comment]
> @donggoing The structure can refer to this link.
> 
> > https://github.com/WangyiNTU/Point-supervised-crowd-detection/blob/701750757adf7015d091a114acbc0f43da2d2772/keras_csp/resnet50_full_res.py#L205

Thanks! Also I want to know when you can release the training and testing code on the SH dataset. I want to implement your method using PyTorch for SH, but it seems a bit difficult to reproduce the effect.

**Comment by WangyiNTU** [comment]
> > @donggoing The structure can refer to this link.
> > > https://github.com/WangyiNTU/Point-supervised-crowd-detection/blob/701750757adf7015d091a114acbc0f43da2d2772/keras_csp/resnet50_full_res.py#L205
> 
> Thanks! Also I want to know when you can release the training and testing code on the SH dataset. I want to implement your method using PyTorch for SH, but it seems a bit difficult to reproduce the effect.

@donggoing Hi, I have updated the codes for training and testing SH dataset. The delay is due to my thesis things. We also plan to give a Pytroch implementation with better performance and easy to debug.

**Comment by donggoing** [comment]
@WangyiNTU Thanks a lot! It works now.
