### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jieruyao49** [WangyiNTU/Point-supervised-crowd-detection#4]
I installed python2.7 and requirements.txt according to the README.md. When I'm running train_wider.py, the following error is reported :
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/PycharmProjects/crowd/Point-supervised-crowd-detection-main/train_wider.py", line 7, in <module>
    from keras.utils import generic_utils
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
    class DescriptorBase(metaclass=DescriptorMetaclass):
                                  ^
SyntaxError: invalid syntax
```

My installation package is shown below：

```
absl-py                   0.14.0                    <pip>
astor                     0.8.1                     <pip>
backports.weakref         1.0.post1                 <pip>
certifi                   2016.2.28                py27_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
easydict                  1.6                       <pip>
enum34                    1.1.10                    <pip>
funcsigs                  1.0.2                     <pip>
futures                   3.3.0                     <pip>
gast                      0.5.2                     <pip>
google-pasta              0.2.0                     <pip>
grpcio                    1.40.0                    <pip>
h5py                      2.10.0                    <pip>
joblib                    0.10.3                    <pip>
Keras                     2.0.6                     <pip>
Keras-Applications        1.0.8                     <pip>
Keras-Preprocessing       1.1.2                     <pip>
Markdown                  3.1.1                     <pip>
mock                      3.0.5                     <pip>
numpy                     1.16.0                    <pip>
olefile                   0.46                      <pip>
opencv-python             3.4.1.15                  <pip>
openssl                   1.0.2l                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
Pillow                    4.0.0                     <pip>
pip                       9.0.1                    py27_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
protobuf                  3.18.0                    <pip>
python                    2.7.13                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
PyYAML                    5.4.1                     <pip>
readline                  6.2                           2    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
scipy                     1.2.3                     <pip>
setuptools                36.4.0                   py27_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
setuptools                44.1.1                    <pip>
six                       1.16.0                    <pip>
sqlite                    3.13.0                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
tensorboard               1.14.0                    <pip>
tensorflow-estimator      1.14.0                    <pip>
tensorflow-gpu            1.14.0                    <pip>
termcolor                 1.1.0                     <pip>
Theano                    1.0.5                     <pip>
tk                        8.5.18                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
Werkzeug                  1.0.1                     <pip>
wheel                     0.29.0                   py27_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
wrapt                     1.12.1                    <pip>
zlib                      1.2.11                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
```

**Comment by WangyiNTU** [comment]
> I installed python2.7 and requirements.txt according to the README.md. When I'm running train_wider.py, the following error is reported :
> 
> ```
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/home/PycharmProjects/crowd/Point-supervised-crowd-detection-main/train_wider.py", line 7, in <module>
>     from keras.utils import generic_utils
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
>     from . import utils
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
>     from . import conv_utils
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 3, in <module>
>     from .. import backend as K
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/backend/__init__.py", line 83, in <module>
>     from .tensorflow_backend import *
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
>     import tensorflow as tf
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/tensorflow/__init__.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 7, in <module>
>     from google.protobuf import descriptor as _descriptor
>   File "/home/anaconda3/envs/pscd_pytorch/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
>     class DescriptorBase(metaclass=DescriptorMetaclass):
>                                   ^
> SyntaxError: invalid syntax
> ```
> 
> My installation package is shown below：
> 
> ```
> absl-py                   0.14.0                    <pip>
> astor                     0.8.1                     <pip>
> backports.weakref         1.0.post1                 <pip>
> certifi                   2016.2.28                py27_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> easydict                  1.6                       <pip>
> enum34                    1.1.10                    <pip>
> funcsigs                  1.0.2                     <pip>
> futures                   3.3.0                     <pip>
> gast                      0.5.2                     <pip>
> google-pasta              0.2.0                     <pip>
> grpcio                    1.40.0                    <pip>
> h5py                      2.10.0                    <pip>
> joblib                    0.10.3                    <pip>
> Keras                     2.0.6                     <pip>
> Keras-Applications        1.0.8                     <pip>
> Keras-Preprocessing       1.1.2                     <pip>
> Markdown                  3.1.1                     <pip>
> mock                      3.0.5                     <pip>
> numpy                     1.16.0                    <pip>
> olefile                   0.46                      <pip>
> opencv-python             3.4.1.15                  <pip>
> openssl                   1.0.2l                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> Pillow                    4.0.0                     <pip>
> pip                       9.0.1                    py27_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> protobuf                  3.18.0                    <pip>
> python                    2.7.13                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> PyYAML                    5.4.1                     <pip>
> readline                  6.2                           2    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> scipy                     1.2.3                     <pip>
> setuptools                36.4.0                   py27_1    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> setuptools                44.1.1                    <pip>
> six                       1.16.0                    <pip>
> sqlite                    3.13.0                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> tensorboard               1.14.0                    <pip>
> tensorflow-estimator      1.14.0                    <pip>
> tensorflow-gpu            1.14.0                    <pip>
> termcolor                 1.1.0                     <pip>
> Theano                    1.0.5                     <pip>
> tk                        8.5.18                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> Werkzeug                  1.0.1                     <pip>
> wheel                     0.29.0                   py27_0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> wrapt                     1.12.1                    <pip>
> zlib                      1.2.11                        0    https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
> ```

@jieruyao49 This may come from some environmental problems, and you can follow the [link](https://ask.csdn.net/questions/7512015), which is common when you google it.
`pip install protobuf==3.17.3`
