### ISSUE TITLE
Most of the code is missing comments

### ISSUE THREAD

**Issue by msn199959** [WangyiNTU/Point-supervised-crowd-detection#6]
Recently I was reading the code of this paper, but some code variable names contain "seman" and "ind”, what does that mean? 
For example the"hms" in train_ShanghaiTecha.py and "seman_map" in data_generators.py(calc_gt_center_weights())

**Comment by WangyiNTU** [comment]
@msn199959 Thanks for your interest. Because this work rush to implement the algorithm, we didn't provide more comments. If you use IDE, like Pycharm, you can debug and see the details of the variables. Sorry about that.
